name: Fortify-Scan

on: push #Configurar de acuerdo a politicas de la empresa.

jobs:
  Fortify-Scan:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          scancentral -sscurl ${{secrets.SSC_URL}} -ssctoken ${{secrets.SSC_TOKEN}} start -bt none -upload -application ${{secrets.APPLICATION}} -version ${{secrets.VERSION}} -uptoken ${{secrets.SSC_TOKEN}}
