name: Fortify-Scan-Simplificado

on: push #Configurar de acuerdo a politicas de la empresa.
jobs:
  Fortify-Scan:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          scancentral -sscurl ${{secrets.SSC_URL}} -ssctoken ${{secrets.SSC_TOKEN}} start -bt none -upload -application Eightball -version 1.0 -uptoken ${{secrets.SSC_TOKEN}}
