name: Fortify-Scan

on: push #Configurar de acuerdo a politicas de la empresa.

jobs:
  Fortify-Scan:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          scancentral -sscurl $SSC_URL -ssctoken $SSC_TOKEN start -bt none -upload -application $APPLICATION -version $VERSION -uptoken $SSC_TOKEN
