name: Fortify-Scan

on: push #Configurar de acuerdo a politicas de la empresa.

jobs:
  Fortify-Scan:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          isSSCOnline = $(python3 <ruta de carga>/online.py)
          echo $isSSCOnline
          
          if [$isSSCOnline -eq 200]; then
            scancentral -sscurl $SSC_URL -ssctoken $SSC_TOKEN start -bt none -upload -application $APPLICATION -version $VERSION -uptoken $SSC_TOKEN
            grep "Submitted job and received token:" > jobtoken.txt
            cat jobtoken.txt
            python3 <ruta de carga>/jobtoken.py
          fi
             
