name: Fortify-Scan

on: push #Configurar de acuerdo a politicas de la empresa.

jobs:
  Fortify-Scan:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          isSSCOnline = $(python3 <ruta de carga>/online.py)
          echo $isSSCOnline
          
          if [$isSSCOnline -eq 200]; then
            scancentral -sscurl ${{secrets.SSC_URL}} -ssctoken ${{secrets.SSC_TOKEN}} start -bt none -upload -application ${{secrets.APPLICATION}} -version ${{secrets.VERSION}} -uptoken ${{secrets.SSC_TOKEN}}
            grep "Submitted job and received token:" > jobtoken.txt
            cat jobtoken.txt
            python3 <ruta de carga>/jobtoken.py
          fi
             
