name: Fortify-Scan-Windows

on: push

jobs:
  fortify-SAST:
    runs-on: 
      - self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fortify Scan
        run: |
          $isSSCOnline = $(python.exe C:\pipeline\online.py)
          cd C:\pipeline\
          echo $isSSCOnline
          
          if ($isSSCOnline -eq 200) {
            scancentral -sscurl ${{secrets.SSC_URL}} -ssctoken ${{secrets.SSC_TOKEN}} start -bt none -upload -application Eightball -version 1.0 -uptoken ${{secrets.SSC_TOKEN}} | findstr /B /R /c:"Submitted job and received token:*" > jobtoken.txt
            type jobtoken.txt
            python.exe C:/pipeline/jobToken.py
            
             }
        
          
